packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - core-js
  - esbuild
catalog:
  '@antfu/eslint-config': ^6.4.1
  '@changesets/cli': ^2.29.8
  '@lexical/dragon': 0.38.1
  '@lexical/extension': 0.38.1
  '@lexical/hashtag': 0.38.1
  '@lexical/history': 0.38.1
  '@lexical/html': 0.38.1
  '@lexical/link': 0.38.1
  '@lexical/list': 0.38.1
  '@lexical/mark': 0.38.1
  '@lexical/markdown': 0.38.1
  '@lexical/overflow': 0.38.1
  '@lexical/plain-text': 0.38.1
  '@lexical/rich-text': 0.38.1
  '@lexical/table': 0.38.1
  '@lexical/text': 0.38.1
  '@lexical/utils': 0.38.1
  '@lexical/yjs': 0.38.1
  '@rslib/core': ^0.16.1
  '@types/node': ^20.19.25
  '@vitejs/plugin-vue': ^6.0.1
  '@vue-vine/eslint-config': ^1.1.12
  '@vue-vine/rspack-loader': 1.7.20-beta.1
  '@vue/tsconfig': ^0.8.1
  eslint: ^9.39.1
  lexical: 0.38.1
  tiny-invariant: ^1.3.3
  typescript: ^5.9.3
  vite: npm:rolldown-vite@7.1.14
  vitepress: ^1.6.4
  vue: ^3.5.22
  vue-tsc: ^3.1.0
  vue-vine: ^1.7.20
  vue-vine-tsc: ^1.7.20
  yjs: ^13.6.18
overrides:
  vite: npm:rolldown-vite@7.1.14
