packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.6.0
  '@vue-vine/eslint-config': ^1.1.12
  '@vue-vine/eslint-plugin': ^1.1.12
  eslint: ^9.39.5
  typescript: ~5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0

catalogMode: prefer

onlyBuiltDependencies:
  - core-js
  - esbuild

overrides:
  vite@*: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
